/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.wobr;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class WobrModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public WobrModElements() {
		sounds.put(new ResourceLocation("wobr", "revolver_reload_1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "revolver_reload_1")));
		sounds.put(new ResourceLocation("wobr", "revolver_reload_full_1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "revolver_reload_full_1")));
		sounds.put(new ResourceLocation("wobr", "handmade_revolver_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "handmade_revolver_shot")));
		sounds.put(new ResourceLocation("wobr", "pepper_box_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "pepper_box_shot")));
		sounds.put(new ResourceLocation("wobr", "jitado_shotgun_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "jitado_shotgun_shot")));
		sounds.put(new ResourceLocation("wobr", "elephant_gun_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "elephant_gun_shot")));
		sounds.put(new ResourceLocation("wobr", "crocodile_shotgun_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "crocodile_shotgun_shot")));
		sounds.put(new ResourceLocation("wobr", "failed_shot_rifle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "failed_shot_rifle")));
		sounds.put(new ResourceLocation("wobr", "short_revolver_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "short_revolver_shot")));
		sounds.put(new ResourceLocation("wobr", "failed_shot"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "failed_shot")));
		sounds.put(new ResourceLocation("wobr", "long_revolver_shot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "long_revolver_shot")));
		sounds.put(new ResourceLocation("wobr", "ormath_shaman_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_shaman_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_shaman_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_shaman_hurt")));
		sounds.put(new ResourceLocation("wobr", "ormath_shaman_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_shaman_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_shaman_trade"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_shaman_trade")));
		sounds.put(new ResourceLocation("wobr", "ormath_beast_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_beast_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_beast_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_beast_hurt")));
		sounds.put(new ResourceLocation("wobr", "ormath_beast_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_beast_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_beast_angry"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_beast_angry")));
		sounds.put(new ResourceLocation("wobr", "wind_spirit_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "wind_spirit_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_villager_trade"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_villager_trade")));
		sounds.put(new ResourceLocation("wobr", "ormath_villager_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_villager_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_villager_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_villager_hurt")));
		sounds.put(new ResourceLocation("wobr", "ormath_villager_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_villager_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_warrior_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_warrior_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_warrior_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_warrior_hurt")));
		sounds.put(new ResourceLocation("wobr", "ormath_warrior_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_warrior_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_hunter_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_hunter_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_hunter_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_hunter_hurt")));
		sounds.put(new ResourceLocation("wobr", "ormath_hunter_idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_hunter_idle")));
		sounds.put(new ResourceLocation("wobr", "ormath_rider_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_rider_death")));
		sounds.put(new ResourceLocation("wobr", "ormath_rider_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "ormath_rider_hurt")));
		sounds.put(new ResourceLocation("wobr", "bandit_death"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "bandit_death")));
		sounds.put(new ResourceLocation("wobr", "bandit_hurt"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "bandit_hurt")));
		sounds.put(new ResourceLocation("wobr", "bandit_idle"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "bandit_idle")));
		sounds.put(new ResourceLocation("wobr", "sabre_clash"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "sabre_clash")));
		sounds.put(new ResourceLocation("wobr", "sabre_whoosh"), new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "sabre_whoosh")));
		sounds.put(new ResourceLocation("wobr", "disc_oneironaut"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "disc_oneironaut")));
		sounds.put(new ResourceLocation("wobr", "disc_inside_forest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("wobr", "disc_inside_forest")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("wobr").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == WobrModElements.ModElement.class)
						elements.add((WobrModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(WobrModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new WobrModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		WobrMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final WobrModElements elements;
		protected final int sortid;
		public ModElement(WobrModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
